# Generated by Django 3.0.1 on 2020-05-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('email', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('bedroom', models.IntegerField(blank=True)),
                ('bathroom', models.FloatField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('garage', models.FloatField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate_app.Realtor')),
            ],
        ),
    ]
