# Generated by Django 3.0.1 on 2020-05-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0003_auto_20200512_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='d_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
