# Generated by Django 3.0.1 on 2020-05-20 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0004_auto_20200514_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=150)),
                ('listing_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=180)),
                ('phone', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
